#src/Resources/config/services.yml
parameters:

  #Command controller
  other.pm-bundle.command.reload.class: 'Other\PmBundle\Command\ReloadCommand'
  other.pm-bundle.command.start.class: 'Other\PmBundle\Command\StartCommand'
  other.pm-bundle.command.status.class: 'Other\PmBundle\Command\StatusCommand'
  other.pm-bundle.command.stop.class: 'Other\PmBundle\Command\StopCommand'
  other.pm-bundle.command.config.class: 'Other\PmBundle\Command\ConfigCommand'
  other.pm-bundle.command.slave.class: 'Other\PmBundle\Command\SlaveCommand'

services:

  #Command controller
  other.pm-bundle.command.slave:
    class: "%other.pm-bundle.command.slave.class%"
    tags:
      - { name: console.command, command: pmb:slave }
  other.pm-bundle.command.start:
    class: "%other.pm-bundle.command.start.class%"
    tags:
      - { name: console.command, command: pmb:start }
  other.pm-bundle.command.stop:
    class: "%other.pm-bundle.command.stop.class%"
    tags:
      - { name: console.command, command: pmb:stop }
  other.pm-bundle.command.status:
    class: "%other.pm-bundle.command.status.class%"
    tags:
      - { name: console.command, command: pmb:status }
  other.pm-bundle.command.config:
    class: "%other.pm-bundle.command.config.class%"
    tags:
      - { name: console.command, command: pmb:config }
  other.pm-bundle.command.reload:
    class: "%other.pm-bundle.command.reload.class%"
    tags:
      - { name: console.command, command: pmb:config }
