#src/Resources/config/services.yml
parameters:
  #Request bridge
  pmb.pm_bundle.request_bridge.class: 'PMB\PMBundle\Bridge\RequestBridge'
  pmb.pm_bundle.request_listener.class: 'PMB\PMBundle\Bridge\RequestListener'

  #Command controller
  pmb.pm_bundle.command.start.class: 'PMB\PMBundle\Command\StartCommand'
  pmb.pm_bundle.command.status.class: 'PMB\PMBundle\Command\StatusCommand'
  pmb.pm_bundle.command.stop.class: 'PMB\PMBundle\Command\StopCommand'
  pmb.pm_bundle.command.config.class: 'PMB\PMBundle\Command\ConfigCommand'
  pmb.pm_bundle.command.slave.class: 'PMB\PMBundle\Command\SlaveCommand'

  #Vendors
  pmb.pm_bundle.vendor.loop.class: 'React\EventLoop\LoopInterface'
  pmb.pm_bundle.vendor.http_foundation_factory.class: 'Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory'
  pmb.pm_bundle.vendor.diactoros_factory.class: 'Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory'

services:
  pmb.pm_bundle.request_bridge:
    class: "%pmb.pm_bundle.request_bridge.class%"
    arguments:
      - "@kernel"
      - "@pmb.pm_bundle.vendor.http_foundation_factory"
      - "@pmb.pm_bundle.vendor.diactoros_factory"

  pmb.pm_bundle.request_listener:
    class: "%pmb.pm_bundle.request_listener.class%"
    arguments:
      - "@pmb.pm_bundle.request_bridge"

  #Command controller
  pmb.pm_bundle.command.slave:
    class: "%pmb.pm_bundle.command.slave.class%"
    arguments:
      - "@pmb.pm_bundle.request_listener"
      - "@pmb.pm_bundle.vendor.loop"
    tags:
      - { name: console.command }
  pmb.pm_bundle.command.start:
    class: "%pmb.pm_bundle.command.start.class%"
    tags:
      - { name: console.command }
  pmb.pm_bundle.command.stop:
    class: "%pmb.pm_bundle.command.stop.class%"
    tags:
      - { name: console.command }
  pmb.pm_bundle.command.status:
    class: "%pmb.pm_bundle.command.status.class%"
    tags:
      - { name: console.command }
  pmb.pm_bundle.command.config:
    class: "%pmb.pm_bundle.command.config.class%"
    tags:
      - { name: console.command }

  #Vendors
  pmb.pm_bundle.vendor.loop:
    class: "%pmb.pm_bundle.vendor.loop.class%"
    factory: ['React\EventLoop\Factory', 'create']

  pmb.pm_bundle.vendor.http_foundation_factory:
    class: "%pmb.pm_bundle.vendor.http_foundation_factory.class%"

  pmb.pm_bundle.vendor.diactoros_factory:
    class: "%pmb.pm_bundle.vendor.diactoros_factory.class%"
